name: "Prompt Improvement: Copilot Agent"
description: "Assign the Copilot coding agent to improve prompts with incremental, validated changes."
title: "[Prompt Improvement] <short title>"
labels: ["copilot-agent", "prompt-improvement"]
assignees: ["github-copilot-agent"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to delegate iterative prompt improvements to GitHub Copilot coding agent.
        The agent will create a new branch, open a PR, and iterate based on your PR review comments.
  - type: input
    id: scope
    attributes:
      label: Target files / scope
      description: "Paths or globs of prompts to improve (e.g., user_prompts/**, prompt_engineering_assistant.system.prompt.md)."
      placeholder: "user_prompts/**"
    validations:
      required: true
  - type: dropdown
    id: improvement_type
    attributes:
      label: IMPROVEMENT_TYPE
      description: "Defines the scope of improvements."
      options:
        - incremental
        - comprehensive
        - targeted
      default: 0
    validations:
      required: true
  - type: input
    id: change_threshold
    attributes:
      label: CHANGE_THRESHOLD
      description: "Percentage threshold for total changes (default 15%)."
      placeholder: "15%"
    validations:
      required: false
  - type: dropdown
    id: optimization_focus
    attributes:
      label: OPTIMIZATION_FOCUS
      description: "Primary optimization goal"
      options:
        - all
        - clarity
        - redundancy
        - modularity
      default: 0
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals and Success Criteria
      description: "Define the specific goals and measurable success criteria."
      placeholder: |
        Goals:
        - Reduce redundancy without altering behavior
        - Improve clarity and remove ambiguity
        Success Criteria:
        - Maintain all capabilities and guardrails
        - ≤ 15% diff total change
    validations:
      required: true
  - type: textarea
    id: instructions
    attributes:
      label: Instructions for Copilot
      description: |
        High-level guidance for the agent. It will use the repository's prompt system and the custom chat mode content in .github/chatmodes/prompt_engineering_assistant.chatmode.md.
      placeholder: |
        - Follow the Prompt Engineering Assistant methodology: Research → Test → Improve → Confirm.
        - Preserve all existing functionality and guardrails.
        - Provide clear diffs and concise commit messages.
        - Add/update minimal tests/docs when public behavior changes.
        - Keep changes under the CHANGE_THRESHOLD; prefer incremental PRs.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / Context (optional)
      description: "Links, examples, or constraints."
      placeholder: |
        - Reference prompts: user_prompts/*
        - Keep tone and structure aligned to system prompt.
  - type: markdown
    attributes:
      value: |
        When ready, submit this issue and assign it to Copilot (Assignee: github-copilot-agent). You can also paste the hashtag below in a VS Code chat to hand off:
        
        #github-pull-request_copilot-coding-agent
