# Knowledge Base Validation Workflow
# 
# This workflow validates JSON files in knowledge_base/ against their schemas
# to ensure data integrity and catch errors early.
#
# Status: READY TO ENABLE
# To enable: Uncomment the 'on:' section below
#
# Note: Currently disabled because user_requirements.json and design_decisions.json
# are user-generated during workflows. Enable this when you want to enforce
# schema validation on commits.

# Uncomment to enable:
# on:
#   push:
#     branches: [ main, develop ]
#     paths:
#       - 'knowledge_base/*.json'
#       - 'knowledge_base/schemas/*.json'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - 'knowledge_base/*.json'
#       - 'knowledge_base/schemas/*.json'

# Manually triggerable
on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Validate knowledge base JSON files
      run: |
        python tests/validate_knowledge_base.py
    
    - name: Report results
      if: always()
      run: |
        echo "Validation complete. Check output above for results."

# Future enhancements:
# - Add markdown linting
# - Add link checking
# - Add security scanning
# - Add prompt engineering validation
